# Correçõe dos dados - Anchieta

### Importações

In [1]:
import pandas as pd
from datetime import datetime, timedelta
import shutil

### Código

In [2]:
#Importação das tabelas:
anchi_1999_fev = pd.read_fwf(r'D:\Estudo\Oficina de Pesquisa\Dados Brutos\Anchieta\anchieta_199902_Plv.txt')
anchi_1999_mar = pd.read_fwf(r'D:\Estudo\Oficina de Pesquisa\Dados Brutos\Anchieta\anchieta_199903_Plv.txt')

In [3]:
anchi_1999_fev

           Relatório Pluviométrico da Estação: Anchieta
0     Dados normalizados para o Horário Brasileiro d...
1     Dia         Hora      HBV   15 min   01 h   04...
2     01/02/1999  00:08:40  HBV      0.0    0.0    0...
3     01/02/1999  00:23:40  HBV      0.0    0.0    0...
4     01/02/1999  00:38:40  HBV      0.0    0.0    0...
...                                                 ...
2689  28/02/1999  22:53:40           0.0    0.0    0...
2690  28/02/1999  23:08:40           0.0    0.0    0...
2691  28/02/1999  23:23:40           0.0    0.0    0...
2692  28/02/1999  23:38:40           0.0    0.0    0...
2693  28/02/1999  23:53:40           0.0    0.0    0...

[2694 rows x 1 columns]

In [4]:
df_remove = anchi_1999_fev.loc[(anchi_1999_fev['Relatório Pluviométrico da Estação: Anchieta'] == "Dados normalizados para o Horário Brasileiro de Verão (HBV)") |
                      (anchi_1999_fev['Relatório Pluviométrico da Estação: Anchieta'] == "Dia         Hora      HBV   15 min   01 h   04 h   24 h   96 h")|
                      (anchi_1999_fev['Relatório Pluviométrico da Estação: Anchieta'] == "Relatório Pluviométrico da Estação: Anchieta")]
anchi_1999_fev = anchi_1999_fev.drop(df_remove.index)
anchi_1999_mar = anchi_1999_mar.drop(df_remove.index)

In [5]:
anchi_1999_fev.to_csv(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_fev.csv', index = False, sep = "\t")
anchi_1999_mar.to_csv(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_mar.csv', index = False, sep = "\t")

In [6]:
#Criando um arquivo txt
shutil.copy(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_fev.csv',r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_fev.txt')
shutil.copyfile(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_mar.csv',r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_mar.txt')

'D:\\Estudo\\Oficina de Pesquisa\\Teste\\anchi_1999_mar.txt'

In [7]:
try:
    with open('anchi_1999_fev.txt', 'r') as fr:
        lines = fr.readlines()
  
        with open('anchi_1999_fev.txt', 'w') as fw:
            for line in lines:
                
                # find() returns -1 
                # if no match found
                if line.find('Relatório') == -1:
                    fw.write(line)
    print("Deleted")
except:
    print("Oops! someting error")

Oops! someting error

In [8]:
try:
    with open('anchi_1999_mar.txt', 'r') as fr:
        lines = fr.readlines()
  
        with open('anchi_1999_mar.txt', 'w') as fw:
            for line in lines:
                
                # find() returns -1 
                # if no match found
                if line.find('Relatório') == -1:
                    fw.write(line)
    print("Deleted")
except:
    print("Oops! someting error")

Oops! someting error

### Reimportando os dados

In [15]:
colunas = ['Dia', 'Hora','HBV','15 min','01 h','04 h','24 h','96 h']
anchi_1999_fev2 = pd.read_fwf(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_fev.txt', names = colunas)
anchi_1999_mar2 = pd.read_fwf(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_1999_mar.txt', names = colunas)

#  Criando Fevereiro 31 dias

In [20]:
#Concatenando as Tabelas:
anchi_fev31_1999 = pd.concat([anchi_1999_fev2, anchi_1999_mar2], ignore_index = True)
anchi_fev31_1999

             Dia      Hora  HBV 15 min 01 h 04 h 24 h  96 h
0     01/02/1999  00:08:40  HBV    0.0  0.0  0.0  8.4  25.5
1     01/02/1999  00:23:40  HBV    0.0  0.0  0.0  8.4  25.5
2     01/02/1999  00:38:40  HBV    0.0  0.0  0.0  8.4  25.5
3     01/02/1999  00:53:40  HBV    0.0  0.0  0.0  8.4  25.5
4     01/02/1999  01:08:40  HBV    0.0  0.0  0.0  8.4  25.5
...          ...       ...  ...    ...  ...  ...  ...   ...
5663  31/03/1999  22:53:40  0.0    0.0  0.0  0.5  1.2   NaN
5664  31/03/1999  23:08:40  0.0    0.0  0.0  0.5  1.2   NaN
5665  31/03/1999  23:23:40  0.0    0.0  0.0  0.5  1.2   NaN
5666  31/03/1999  23:38:40  0.0    0.0  0.0  0.5  1.2   NaN
5667  31/03/1999  23:53:40  0.0    0.0  0.0  0.5  1.2   NaN

[5668 rows x 8 columns]

In [17]:
# Efetivamente 
anchi_fev31_1999 = anchi_fev31_1999.loc[0:2979]

In [24]:
hora = timedelta(hours=1)

for i in range(0,anchi_fev31_1999.shape[0]):
    if anchi_fev31_1999.HBV[i] == "HBV":
        data_hbv = datetime.strptime(anchi_fev31_1999.Dia[i]+" "+anchi_fev31_1999.Hora[i],"%d/%m/%Y %H:%M:%S")
        correcao = data_hbv - hora
        data_corrigida = datetime.strftime(correcao,"%d/%m/%Y %H:%M:%S")
        dia, horario = data_corrigida.split()
        anchi_fev31_1999.iat[i,0] = dia
        anchi_fev31_1999.iat[i,1] = horario

In [26]:
anchi_fev31_1999

           Dia      Hora  HBV 15 min 01 h 04 h 24 h  96 h
0   31/01/1999  23:08:40  HBV    0.0  0.0  0.0  8.4  25.5
1   31/01/1999  23:23:40  HBV    0.0  0.0  0.0  8.4  25.5
2   31/01/1999  23:38:40  HBV    0.0  0.0  0.0  8.4  25.5
3   31/01/1999  23:53:40  HBV    0.0  0.0  0.0  8.4  25.5
4   31/01/1999  22:08:40  HBV    0.0  0.0  0.0  8.4  25.5
5   31/01/1999  22:23:40  HBV    0.0  0.0  0.0  8.4  25.5
6   31/01/1999  22:38:40  HBV    0.0  0.0  0.0  8.4  25.5
7   31/01/1999  22:53:40  HBV    0.0  0.0  0.0  8.4  25.5
8   31/01/1999  23:08:40  HBV    0.0  0.0  0.0  8.4  25.5
9   31/01/1999  23:23:40  HBV    0.0  0.0  0.0  8.4  25.5
10  31/01/1999  23:38:40  HBV    0.0  0.0  0.0  8.4  25.5
11  31/01/1999  23:53:40  HBV    0.0  0.0  0.0  8.4  25.5
12  01/02/1999  00:08:40  HBV    0.0  0.0  0.0  8.4  25.5
13  01/02/1999  00:23:40  HBV    0.0  0.0  0.0  8.4  25.5
14  01/02/1999  00:38:40  HBV    0.0  0.0  0.0  8.4  25.5
15  01/02/1999  00:53:40  HBV    0.0  0.0  0.0  8.4  25.5
16  01/02/1999  01:08:40  HBV    0.0  0.0  0.0  8.4  25.5
17  01/02/1999  01:23:40  HBV    0.0  0.0  0.0  8.4  25.3
18  01/02/1999  01:38:40  HBV    0.0  0.0  0.0  8.4  25.3
19  01/02/1999  01:53:40  HBV    0.0  0.0  0.0  8.4  25.3
20  01/02/1999  02:08:40  HBV    0.0  0.0  0.0  8.4  25.3
21  01/02/1999  02:23:40  HBV    0.0  0.0  0.0  8.4  25.3
22  01/02/1999  02:38:40  HBV    0.0  0.0  0.0  8.4  25.1
23  01/02/1999  02:53:40  HBV    0.0  0.0  0.0  8.4  25.1
24  01/02/1999  03:08:40  HBV    0.0  0.0  0.0  8.4  25.1
25  01/02/1999  03:23:40  HBV    0.0  0.0  0.0  8.4  25.1
26  01/02/1999  03:38:40  HBV    0.0  0.0  0.0  8.4  25.1
27  01/02/1999  03:53:40  HBV    0.0  0.0  0.0  8.4  25.1
28  01/02/1999  04:08:40  HBV    0.0  0.0  0.0  8.4  25.1
29  01/02/1999  04:23:40  HBV    0.0  0.0  0.0  8.4  25.1
30  01/02/1999  04:38:40  HBV    0.0  0.0  0.0  8.4  25.1
31  01/02/1999  04:53:40  HBV    0.0  0.0  0.0  8.4  25.1
32  01/02/1999  05:08:40  HBV    0.0  0.0  0.0  8.4  25.1
33  01/02/1999  05:23:40  HBV    0.0  0.0  0.0  8.4  25.1
34  01/02/1999  05:38:40  HBV    0.0  0.0  0.0  8.4  25.1
35  01/02/1999  05:53:40  HBV    0.0  0.0  0.0  8.4  25.1
36  01/02/1999  06:08:40  HBV    0.0  0.0  0.0  8.4  25.1
37  01/02/1999  06:23:40  HBV    0.0  0.0  0.0  8.4  25.1
38  01/02/1999  06:38:40  HBV    0.0  0.0  0.0  8.4  25.1
39  01/02/1999  06:53:40  HBV    0.0  0.0  0.0  8.4  25.1
40  01/02/1999  07:08:40  HBV    0.0  0.0  0.0  8.4  25.1
41  01/02/1999  07:23:40  HBV    0.0  0.0  0.0  8.4  25.1
42  01/02/1999  07:38:40  HBV    0.0  0.0  0.0  8.4  25.1
43  01/02/1999  07:53:40  HBV    0.0  0.0  0.0  8.4  25.1
44  01/02/1999  08:08:40  HBV    0.0  0.0  0.0  8.4  25.1
45  01/02/1999  08:23:40  HBV    0.0  0.0  0.0  8.4  25.1
46  01/02/1999  08:38:40  HBV    0.0  0.0  0.0  8.4  25.1
47  01/02/1999  08:53:40  HBV    0.0  0.0  0.0  8.4  25.1
48  01/02/1999  09:08:40  HBV    0.0  0.0  0.0  8.4  25.1
49  01/02/1999  09:23:40  HBV    0.0  0.0  0.0  8.4  25.1

In [14]:
anchi_fev31_1999.to_csv(r'D:\Estudo\Oficina de Pesquisa\Teste\anchi_fev31_1998.csv', index = False, sep = "\t")