In [2]:
import pandas as pd

In [3]:
Fev31_15min = []
FevNorm_15min = []
anos = ['1997','1998','1999','2000','2001','2002','2003','2004','2005',
        '2006','2007','2008','2009','2010','2011','2012','2013','2014',
        '2015','2016','2017','2018','2019','2020','2021','2022']

In [5]:
pasta = input('Digite a Estação: ')
diretorio = r'D:\Estudo\Oficina de Pesquisa\Dados Tradados'

#Tratando as entradas:
tamanho = pasta.split()
if len(tamanho) != 1:
    elemento = ('_'.join(tamanho)).lower()
else:
    elemento = pasta.lower()

#Fevereiro de 31 Dias:
for ano in anos:
    arquivo = pd.read_csv(diretorio+'\\'+pasta+'\\'+elemento+'_fev31_'+ano+'.csv', sep=',')
    arquivo[arquivo['15 min'] == 'ND'] = 0 
    arquivo[['15 min']] = arquivo[['15 min']].apply(pd.to_numeric)
    soma = arquivo['15 min'].sum()
    Fev31_15min.append(soma)

#Fevereiro Normal:
for ano in anos:
    arquivo = pd.read_csv(diretorio+'\\'+pasta+'\\'+elemento+'_Normal_'+ano+'.csv', sep=',')
    arquivo[arquivo['15 min'] == 'ND'] = 0 
    arquivo[['15 min']] = arquivo[['15 min']].apply(pd.to_numeric)
    soma = arquivo['15 min'].sum()
    FevNorm_15min.append(soma)

lista_de_tuplas = list(zip(anos,Fev31_15min,FevNorm_15min))

df = pd.DataFrame(lista_de_tuplas, columns=['Anos','Fev31','FevNormal'])
df['Fev31N'] = df['Fev31'] /31
df.to_csv(diretorio+'\\'+elemento+'_Final.csv', index = False)

df

Digite a Estação: Anchieta

    Anos  Fev31  FevNormal     Fev31N
0   1997   95.7       65.4   3.087097
1   1998  301.3      288.7   9.719355
2   1999  131.7      130.9   4.248387
3   2000   96.5       96.3   3.112903
4   2001   95.4       95.4   3.077419
5   2002  178.0      178.0   5.741935
6   2003    1.6        1.6   0.051613
7   2004  129.0      129.0   4.161290
8   2005  145.2       69.4   4.683871
9   2006  192.6      192.6   6.212903
10  2007  131.0      131.0   4.225806
11  2008  264.2      253.4   8.522581
12  2009  188.6      188.6   6.083871
13  2010  132.4       57.6   4.270968
14  2011   39.2       34.4   1.264516
15  2012   31.2       31.2   1.006452
16  2013  125.6      116.8   4.051613
17  2014   26.2       26.2   0.845161
18  2015  122.2      122.2   3.941935
19  2016  191.2      188.8   6.167742
20  2017   60.4       59.2   1.948387
21  2018  178.6      177.4   5.761290
22  2019  328.0      242.4  10.580645
23  2020  493.0      343.4  15.903226
24  2021  209.0      209.0   6.741935
25  2022  131.8      131.8   4.251613

In [ ]:
    arquivo = pd.read_csv(r'D:\Estudo\Oficina de Pesquisa\Dados Tradados\cidade_de_deus_Final.csv', sep=';')
    arquivo